name: Makefile CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    container: scummvm/dockerized-toolchains:ps3

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make -j$(nproc)
